### ISSUE TITLE
test failures may show wrong outputs

### ISSUE THREAD

**Issue by clux** [clux/bandage#9]
If two structs are not `t.eq` there is usually a reason, but this reason can be obscured by subsequent modification of one of those two structs. These messages can be processed after when the error diff is printed. Need to figure out why that is and if it can be avoided.

E.g. here is what it should look like (achieved by having a `return` after the `t.eq` call):

``` yaml
  not ok 68 t1 matches
    ---
      operator: eq
      expected: [ { id: { m: 1, r: 1, s: 1 }, p: [ 1, 3, 6, 8 ] }, { id: { m: 1, r: 1, s: 1 }, p: [ 2, 4, 5, 7 ] } ]
      actual: [ { id: { m: 1, r: 1, s: 1 }, p: [ 1, 3, 6, 8 ] }, { id: { m: 2, r: 1, s: 1 }, p: [ 2, 4, 5, 7 ] } ]
      at: null (/home/clux/repos/tournament/ffa-tb/test/results.test.js:12:5)
    ...
```

and here is what it actually looks like:

``` yaml
  not ok 68 t1 matches
    ---
      operator: eq
      expected: [ { id: { m: 1, r: 1, s: 1 }, p: [ 1, 3, 6, 8 ] }, { id: { m: 1, r: 1, s: 1 }, p: [ 2, 4, 5, 7 ] } ]
      actual: [ { id: { m: 1, r: 1, s: 1 }, m: [ 4, 3, 2, 1 ], p: [ 1, 3, 6, 8 ] }, { id: { m: 2, r: 1, s: 1 }, m: [ 4, 3, 2, 1 ], p: [ 2, 4, 5, 7 ] } ]
      at: null (/home/clux/repos/tournament/ffa-tb/test/results.test.js:12:5)
    ...
```
